#ifndef CONFIG_DEFAULTS_H_
#define CONFIG_DEFAULTS_H_

#include "config_types.h"

#ifndef CONFIG_DEVICE_TYPE
#define CONFIG_DEVICE_TYPE DEVICE_NONE
#endif /*CONFIG_DEVICE_TYPE*/

#ifndef CONFIG_NET_WIFI_SSID
#define CONFIG_NET_WIFI_SSID ""
#endif /*CONFIG_NET_WIFI_SSID*/

#ifndef CONFIG_NET_WIFI_PASS
#define CONFIG_NET_WIFI_PASS ""
#endif /*CONFIG_NET_WIFI_PASS*/

#ifndef CONFIG_NET_WIFI_TX_POWER
#define CONFIG_NET_WIFI_TX_POWER WIFI_POW_MAX
#endif /*CONFIG_NET_WIFI_TX_POWER*/

#ifndef CONFIG_NET_WIFI_COUNTRY_CODE
#define CONFIG_NET_WIFI_COUNTRY_CODE "US"
#endif /*CONFIG_NET_WIFI_COUNTRY_CODE*/

#ifndef CONFIG_PORTAL_API_SECRET
#define CONFIG_PORTAL_API_SECRET ""
#endif /*CONFIG_PORTAL_API_SECRET*/

#ifndef CONFIG_PORTAL_WS_URL
#define CONFIG_PORTAL_WS_URL ""
#endif /*CONFIG_PORTAL_WS_URL*/

#ifndef CONFIG_DFU_URL
#define CONFIG_DFU_URL ""
#endif /*CONFIG_DFU_URL*/

#ifndef CONFIG_DFU_SKIP_CN_CHECK
#define CONFIG_DFU_SKIP_CN_CHECK false
#endif /*CONFIG_DFU_SKIP_CN_CHECK*/

#ifndef CONFIG_DFU_SKIP_VERSION_CHECK
#define CONFIG_DFU_SKIP_VERSION_CHECK false
#endif /*CONFIG_DFU_SKIP_VERSION_CHECK*/

#ifndef CONFIG_GEN_LOCK_REVERSED
#define CONFIG_GEN_LOCK_REVERSED false
#endif /*CONFIG_GEN_LOCK_REVERSED*/

#ifndef CONFIG_GEN_READER_LED_REV
#define CONFIG_GEN_READER_LED_REV true
#endif /*CONFIG_GEN_READER_LED_REV*/

#ifndef CONFIG_GEN_RELAY_REV
#define CONFIG_GEN_RELAY_REV false
#endif /*CONFIG_GEN_RELAY_REV*/

#ifndef CONFIG_GEN_DOOR_SENSOR_REV
#define CONFIG_GEN_DOOR_SENSOR_REV true
#endif /*CONFIG_GEN_DOOR_SENSOR_REV*/

#ifndef CONFIG_GEN_DOOR_SENSOR_EN
#define CONFIG_GEN_DOOR_SENSOR_EN false
#endif /*CONFIG_GEN_DOOR_SENSOR_EN*/

#ifndef CONFIG_GEN_DOOR_SENSOR_TIMEOUT
#define CONFIG_GEN_DOOR_SENSOR_TIMEOUT 5
#endif /*CONFIG_GEN_DOOR_SENSOR_TIMEOUT*/

#ifndef CONFIG_GEN_DOOR_OPEN_ALARM_TIMEOUT
#define CONFIG_GEN_DOOR_OPEN_ALARM_TIMEOUT 0
#endif /*CONFIG_GEN_DOOR_OPEN_ALARM_TIMEOUT*/

#ifndef CONFIG_GEN_OUT1_REV
#define CONFIG_GEN_OUT1_REV false
#endif /*CONFIG_GEN_OUT1_REV*/

#ifndef CONFIG_GEN_IN1_REV
#define CONFIG_GEN_IN1_REV true
#endif /*CONFIG_GEN_IN1_REV*/

#ifndef CONFIG_GEN_AUX1_REV
#define CONFIG_GEN_AUX1_REV false
#endif /*CONFIG_GEN_AUX1_REV*/

#ifndef CONFIG_GEN_AUX2_REV
#define CONFIG_GEN_AUX2_REV false
#endif /*CONFIG_GEN_AUX2_REV*/

#ifndef CONFIG_GEN_FIXED_UNLOCK_DELAY
#define CONFIG_GEN_FIXED_UNLOCK_DELAY 7
#endif /*CONFIG_GEN_FIXED_UNLOCK_DELAY*/

#ifndef CONFIG_GEN_RGB_LED_COUNT
#define CONFIG_GEN_RGB_LED_COUNT 0
#endif /*CONFIG_GEN_RGB_LED_COUNT*/

#ifndef CONFIG_GEN_WIEGAND_ENABLED
#define CONFIG_GEN_WIEGAND_ENABLED true
#endif /*CONFIG_GEN_WIEGAND_ENABLED*/

#ifndef CONFIG_GEN_UID_32BIT_MODE
#define CONFIG_GEN_UID_32BIT_MODE false
#endif /*CONFIG_GEN_UID_32BIT_MODE*/

#ifndef CONFIG_BUZZER_EN
#define CONFIG_BUZZER_EN true
#endif /*CONFIG_BUZZER_EN*/

#ifndef CONFIG_BUZZER_REV
#define CONFIG_BUZZER_REV true
#endif /*CONFIG_BUZZER_REV*/

#ifndef CONFIG_BUZZER_BUZZ_ON_SWIPE
#define CONFIG_BUZZER_BUZZ_ON_SWIPE true
#endif /*CONFIG_BUZZER_BUZZ_ON_SWIPE*/

#ifndef CONFIG_BUZZER_ACTION_DELAY
#define CONFIG_BUZZER_ACTION_DELAY 2
#endif /*CONFIG_BUZZER_ACTION_DELAY*/

#ifndef CONFIG_INTLCK_HOST
#define CONFIG_INTLCK_HOST ""
#endif /*CONFIG_INTLCK_HOST*/

#ifndef CONFIG_INTLCK_USER
#define CONFIG_INTLCK_USER ""
#endif /*CONFIG_INTLCK_USER*/

#ifndef CONFIG_INTLCK_PASS
#define CONFIG_INTLCK_PASS ""
#endif /*CONFIG_INTLCK_PASS*/

#ifndef CONFIG_VEND_PRICE
#define CONFIG_VEND_PRICE 250
#endif /*CONFIG_VEND_PRICE*/

#ifndef CONFIG_VEND_MODE
#define CONFIG_VEND_MODE VENDING_HOLD
#endif /*CONFIG_VEND_MODE*/

#ifndef CONFIG_VEND_TOGGLE_TIME
#define CONFIG_VEND_TOGGLE_TIME 1
#endif /*CONFIG_VEND_TOGGLE_TIME*/

#ifndef CONFIG_LCD_EN
#define CONFIG_LCD_EN true
#endif /*CONFIG_LCD_EN*/

#ifndef CONFIG_LCD_ADDRESS
#define CONFIG_LCD_ADDRESS 0x27
#endif /*CONFIG_LCD_ADDRESS*/

#ifndef CONFIG_LCD_COLS
#define CONFIG_LCD_COLS 16
#endif /*CONFIG_LCD_COLS*/

#ifndef CONFIG_LCD_ROWS
#define CONFIG_LCD_ROWS 2
#endif /*CONFIG_LCD_ROWS*/

#ifndef CONFIG_PINS_AUX1
#define CONFIG_PINS_AUX1 2
#endif /*CONFIG_PINS_AUX1*/

#ifndef CONFIG_PINS_AUX2
#define CONFIG_PINS_AUX2 1
#endif /*CONFIG_PINS_AUX2*/

#ifndef CONFIG_PINS_RGB_LED
#define CONFIG_PINS_RGB_LED 37
#endif /*CONFIG_PINS_RGB_LED*/

#ifndef CONFIG_PINS_STATUS_LED
#define CONFIG_PINS_STATUS_LED 38
#endif /*CONFIG_PINS_STATUS_LED*/

#ifndef CONFIG_PINS_READER_LED
#define CONFIG_PINS_READER_LED 5
#endif /*CONFIG_PINS_READER_LED*/

#ifndef CONFIG_PINS_READER_BUZZER
#define CONFIG_PINS_READER_BUZZER 4
#endif /*CONFIG_PINS_READER_BUZZER*/

#ifndef CONFIG_PINS_RELAY
#define CONFIG_PINS_RELAY 36
#endif /*CONFIG_PINS_RELAY*/

#ifndef CONFIG_PINS_LOCK
#define CONFIG_PINS_LOCK 14
#endif /*CONFIG_PINS_LOCK*/

#ifndef CONFIG_PINS_DOOR_SENSOR
#define CONFIG_PINS_DOOR_SENSOR  12
#endif /*CONFIG_PINS_DOOR_SENSOR*/

#ifndef CONFIG_PINS_OUT1
#define CONFIG_PINS_OUT1 35
#endif /*CONFIG_PINS_OUT1*/

#ifndef CONFIG_PINS_IN1
#define CONFIG_PINS_IN1 13
#endif /*CONFIG_PINS_IN1*/

#ifndef CONFIG_PINS_SDA
#define CONFIG_PINS_SDA 48
#endif /*CONFIG_PINS_SDA*/

#ifndef CONFIG_PINS_SCL
#define CONFIG_PINS_SCL 47
#endif /*CONFIG_PINS_SCL*/

#ifndef CONFIG_PINS_UART_TX
#define CONFIG_PINS_UART_TX 15
#endif /*CONFIG_PINS_UART_TX*/

#ifndef CONFIG_PINS_UART_RX
#define CONFIG_PINS_UART_RX 16
#endif /*CONFIG_PINS_UART_RX*/

#ifndef CONFIG_PINS_WIEGAND_ZERO
#define CONFIG_PINS_WIEGAND_ZERO 7
#endif /*CONFIG_PINS_WIEGAND_ZERO*/

#ifndef CONFIG_PINS_WIEGAND_ONE
#define CONFIG_PINS_WIEGAND_ONE 6
#endif /*CONFIG_PINS_WIEGAND_ONE*/

#ifndef CONFIG_DEV_LOG_LEVEL
#define CONFIG_DEV_LOG_LEVEL LOG_WARN
#endif /*CONFIG_DEV_LOG_LEVEL*/

extern const config_t _defaults;

#endif /*CONFIG_DEFAULTS_H_*/